spring:
  application:
    name: campus-club-management
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_club_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8080

jwt:
  secret: campusClubManagementSecretKey2024
  expiration: 86400000

logging:
  level:
    root: INFO
    com.wordcount: DEBUG